### 1. Imports

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.datasets import fetch_california_housing

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet
)

from sklearn.metrics import (r2_score, mean_squared_error)

### 2. Loading Dataset

In [3]:
housing = fetch_california_housing()

In [4]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [5]:
df = pd.DataFrame(data=housing['data'],columns=housing['feature_names'])
df['Price'] = housing['target']

In [6]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

### 3. Understanding the data

In [7]:
df.shape

(20640, 9)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   Price       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [9]:
# any missing values
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MedInc,20640.0,3.870671,1.899822,0.499900,2.563400,3.534800,4.743250,15.000100
HouseAge,20640.0,28.639486,12.585558,1.000000,18.000000,29.000000,37.000000,52.000000
AveRooms,20640.0,5.429000,2.474173,0.846154,4.440716,5.229129,6.052381,141.909091
AveBedrms,20640.0,1.096675,0.473911,0.333333,1.006079,1.048780,1.099526,34.066667
Population,20640.0,1425.476744,1132.462122,3.000000,787.000000,1166.000000,1725.000000,35682.000000
AveOccup,20640.0,3.070655,10.386050,0.692308,2.429741,2.818116,3.282261,1243.333333
Latitude,20640.0,35.631861,2.135952,32.540000,33.930000,34.260000,37.710000,41.950000
Longitude,20640.0,-119.569704,2.003532,-124.350000,-121.800000,-118.490000,-118.010000,-114.310000
Price,20640.0,2.068558,1.153956,0.149990,1.196000,1.797000,2.647250,5.000010

### 4. Seprate Feature and Target

In [11]:
X = df.drop(columns="Price")
y = df["Price"]

In [12]:
X.shape , y.shape

((20640, 8), (20640,))

### 5. Train-Test Split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

### 6. Standardization (so that all the features comes to the same scale)

In [14]:
print(X_train.shape ,X_test.shape)

(16512, 8) (4128, 8)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
y_train.to_numpy().reshape(-1,1)
y_test.to_numpy().reshape(-1,1)

array([[0.477  ],
       [0.458  ],
       [5.00001],
       ...,
       [5.00001],
       [0.723  ],
       [1.515  ]], shape=(4128, 1))

### 7. Training the baseline model

In [17]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [18]:
y_pred = lr.predict(X_test)

In [19]:
print("MSE :", mean_squared_error(y_test, y_pred))
print("R²  :", r2_score(y_test, y_pred))

MSE : 0.5558915986952444
R²  : 0.5757877060324508

In [20]:
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": lr.coef_
})

coef_df

      Feature  Coefficient
0      MedInc     0.854383
1    HouseAge     0.122546
2    AveRooms    -0.294410
3   AveBedrms     0.339259
4  Population    -0.002308
5    AveOccup    -0.040829
6    Latitude    -0.896929
7   Longitude    -0.869842

## 1. Ridge Regression

In [63]:
ridge = Ridge(alpha=20.0)
ridge.fit(X_train,y_train)
ridge_pred = ridge.predict(X_test)

In [64]:
print("MSE :", mean_squared_error(y_test, ridge_pred))
print("R² :", r2_score(y_test, ridge_pred))

MSE : 0.5552014108735703
R² : 0.5763144025318907

In [65]:
#### Comparing coefficeint

In [66]:

coef = pd.DataFrame({
    "Feature" : X.columns,
     "Liner Coef" : lr.coef_,
    "Ridge Coef" : ridge.coef_
})

In [67]:
coef

      Feature  Liner Coef  Ridge Coef
0      MedInc    0.854383    0.853230
1    HouseAge    0.122546    0.124067
2    AveRooms   -0.294410   -0.290413
3   AveBedrms    0.339259    0.334253
4  Population   -0.002308   -0.001808
5    AveOccup   -0.040829   -0.040904
6    Latitude   -0.896929   -0.881987
7   Longitude   -0.869842   -0.854704

## 2. Lasso

In [80]:
# let's try with lasso
lasso = Lasso(alpha=0.1)
lasso.fit(X_train,y_train)
lasso_pred = lasso.predict(X_test)

In [81]:
print("MSE :", mean_squared_error(y_test, lasso_pred))
print("R² :", r2_score(y_test, lasso_pred))

MSE : 0.6796290284328825
R² : 0.48136113250290735

In [83]:

coef = pd.DataFrame({
    "Feature" : X.columns,
     "Liner Coef" : lr.coef_,
    "Ridge Coef" : ridge.coef_,
    "Lasso Coef" : lasso.coef_
})
coef

      Feature  Liner Coef  Ridge Coef  Lasso Coef
0      MedInc    0.854383    0.853230    0.710598
1    HouseAge    0.122546    0.124067    0.106453
2    AveRooms   -0.294410   -0.290413   -0.000000
3   AveBedrms    0.339259    0.334253    0.000000
4  Population   -0.002308   -0.001808   -0.000000
5    AveOccup   -0.040829   -0.040904   -0.000000
6    Latitude   -0.896929   -0.881987   -0.011469
7   Longitude   -0.869842   -0.854704   -0.000000

Lasso performs feature selection by shrinking coefficients of less important features all the way to exactly zero.

It's not necessarily that features are completely useless before applying Lasso; rather, when features are correlated or weak predictors, Lasso zeroes out redundant ones to simplify the model.

## 3. Elastic Net

In [104]:
elastic_net = ElasticNet(alpha=0.03 , l1_ratio=0.2)
elastic_net.fit(X_train,y_train)
elastic_pred = elastic_net.predict(X_test)

In [105]:
print("MSE :", mean_squared_error(y_test, elastic_pred))
print("R² :", r2_score(y_test, elastic_pred))

MSE : 0.5550656820255372
R² : 0.5764179800029602

In [106]:
coef = pd.DataFrame({
    "Feature" : X.columns,
     "Liner Coef" : lr.coef_,
    "Ridge Coef" : ridge.coef_,
    "Lasso Coef" : lasso.coef_,
    "Elastic coef" : elastic_net.coef_
})
coef

      Feature  Liner Coef  Ridge Coef  Lasso Coef  Elastic coef
0      MedInc    0.854383    0.853230    0.710598      0.800539
1    HouseAge    0.122546    0.124067    0.106453      0.142132
2    AveRooms   -0.294410   -0.290413   -0.000000     -0.160071
3   AveBedrms    0.339259    0.334253    0.000000      0.190341
4  Population   -0.002308   -0.001808   -0.000000      0.000000
5    AveOccup   -0.040829   -0.040904   -0.000000     -0.034917
6    Latitude   -0.896929   -0.881987   -0.011469     -0.630707
7   Longitude   -0.869842   -0.854704   -0.000000     -0.596133